export const feminineFixture = '{{also|kuche}} ==German== ===Etymology=== From {{inh|de|goh|chuhhina}}, from late {{inh|de|gem-pro|*kukinǭ}}, from {{der|de|VL.|*cocīna}}, from {{der|de|la|coquīna}}. See there for cognates and details. ===Pronunciation=== * {{IPA|/ˈkʏçə/|lang=de}} {{a|standard}} ** {{audio|De-at-Küche.ogg|audio (Austria)|lang=de}} * {{IPA|/ˈkyːçə/|lang=de}} {{a|sometimes in Low German areas}} ** {{audio|De-Küche.ogg|Audio|lang=de}} ===Noun=== {{de-noun|f||Küchen}} # [[kitchen]] {{gloss|room}} # {{l|en|cuisine}} {{gloss|cooking traditions}} ====Declension==== {{de-decl-noun-f|n}} ====Derived terms==== * {{l|de|küchen-}} * {{l|de|Küchenmaschine}} ===Further reading=== * {{R:Duden}} [[Category:de:Rooms]]';

export const masculineFixture = '{{also|honig}} ==German== {{wikipedia|lang=de}} [[Image:Runny hunny.jpg|thumb|ein Honigglas mit Honig]]  ===Etymology=== From {{inh|de|gmh|}}, from {{inh|de|goh|honag}}, from {{inh|de|gem-pro|*hunagą}}.  ===Pronunciation=== * {{IPA|/ˈhoːnɪç/|lang=de}} * {{hyphenation|Ho|nig|lang=de}} * {{audio|De-Honig.ogg|Audio|lang=de}}  ===Noun=== {{de-noun|m||Honige}}  # [[honey]]  ====Declension==== {{de-decl-noun-m|s|e}}  ====Synonyms==== * {{l|de|Bienenhonig}}  ====Hypernyms==== * {{l|de|Lebensmittel}}  ====Hyponyms==== * {{l|de|Akazienhonig}} * {{l|de|Biohonig}} * {{l|de|Blatthonig}} * {{l|de|Blütenhonig}} * {{l|de|Glatthonig}} * {{l|de|Heidehonig}} * {{l|de|Honigtauhonig}} * {{l|de|Kleehonig}} * {{l|de|Landhonig}} * {{l|de|Lavendelhonig}} * {{l|de|Lindenblütenhonig}} * {{l|de|Naturhonig}} * {{l|de|Rapshonig}} * {{l|de|Tannenhonig}} * {{l|de|Waldhonig}} * {{l|de|Wildhonig}}  ====Derived terms==== * {{l|de|Honigbiene|g=f}}  ===Further reading=== * {{R:Canoo}} * {{R:Duden}} * {{R:DWDS}} * {{R:Grimm}} * {{R:UniLeipzig}}';

export const neuterFixture = '==German== ===Alternative forms=== * {{alter|de|Centrum||pre-1901}} ===Etymology=== Borrowed from {{bor|de|la|centrum|t=centre}}, from {{der|de|grc|κέντρον|t=centre of a circle, thorn}}. ===Pronunciation=== * {{IPA|/ˈt͡sɛntʁʊm/|lang=de}} * {{audio|De-Zentrum.ogg|Audio|lang=de}} ===Noun=== {{de-noun|n||Zentren}} # [[center]], [[centre]]; [[central]] [[point]] #: {{syn|de|Mitte|Mittelpunkt|Kern|Hauptsache}} #: {{ant|de|Rand|Hülle|Oberfläche|Peripherie|Nebensache}} # {{lb|de|politics}} the [[centre]], the…he [[space]]s d4, d5, e4, e5 on a [[chessboard]] ====Declension==== {{de-decl-noun-n|s|pl=Zentren|n}} ====Derived terms==== {{der3 |{{l|de|Einkaufszentrum}} |{{l|de|Kontrollzentrum}} |{{l|de|Stadtzentrum}} |lang=de}} ===Further reading=== * {{R:Duden}} ---- ==Hunsrik== ===Pronunciation=== * {{IPA|/ˈt͡sɛntrum/|lang=hrx}} ===Noun=== {{head|hrx|noun|g=n|plural|Zentre}} # [[center]] ===Further reading=== * [https://hunsriqueanoriograndense.wordpress.com/dicionario-werterbuch/ Online Hunsrik Dictionary]';

export const fixtureWithDiminutive = '{{also|lampe|lampé}} ==German== ===Etymology=== From {{etyl|gmh|de}} {{m|gmh|lampe}}. ===Pronunciation=== * {{IPA|/ˈlampə/|lang=de}} * {{audio|De-Lampe.ogg|audio|lang=de}} ===Noun=== {{de-noun|f||Lampen|Lämpchen|dim2=Lämplein}} # [[lamp]], [[light]] {{gloss|piece of furniture, or fixture mounted on a wall or ceiling, holding one or more electric light sockets}} # [[bulb]], [[light bulb]] {{gloss|evacuated glass bulb containing a metal filament or an article that resembles such a bulb}} ====Declension==== {{de-decl-noun-f|n}} ====Related terms==== * {{l|de|Lampenschirm}} * {{l|de|Lavalampe}} * {{l|de|Taschenlampe}} * {{l|de|Lampion}} * {{l|de|Stehlampe}} * {{l|de|Meister Lampe}} * {{l|de|Schreibtischlampe}} ===Anagrams=== * {{l|de|Ampel}} * {{l|de|Palme}}';

export const masculineFixtureWithGenderedForm = '==German== ===Pronunciation=== * {{audio|De-Briefträger.ogg|Audio|lang=de}} ===Noun=== {{de-noun|m|Briefträgers|Briefträger|f=Briefträgerin}} # [[mailman]], [[postman]], [[postie]], [[letter carrier]], [[mail carrier]], [[mailperson]] (male or of unspecified sex) ====Declension==== {{de-decl-noun-m|s}} ====Synonyms==== * {{l|de|Briefzusteller}} * {{l|de|Postbote}} ===Further reading=== * {{R:Duden}} [[Category:de:Occupations]] [[Category:de:Post]]';

export const feminineFixtureWithGenderedForm = '==German== ===Etymology=== {{suffix|Student|in|lang=de}} ===Noun=== {{de-noun|f||Studentinnen|m=Student}} # female [[student]] ====Declension==== {{de-decl-noun-f|nen}} ===Further reading=== * {{R:Duden}}';

export const feminineFixtureWithImplicitEnPlural = '==German== ===Pronunciation=== * {{audio|de|De-Sitzung.ogg|Audio}} ===Noun=== {{de-noun|f}} # [[meeting]] # [[session]] # [[assembly]] # [[sitting]] ====Synonyms==== * {{sense|meeting}} {{l|de|Besprechung}} * {{sense|session}} {{l|de|Sitzungsperiode}} * {{sense|assembly}} {{l|de|Versammlung}} ====See also==== * {{l|de|sitzen}} ===Further reading=== * {{R:Duden}}';
